// Copyright 2024 The dryft Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is generated by the build system. Do not edit manually.

#ifndef CHROME_GRIT_NOSTR_RESOURCES_H_
#define CHROME_GRIT_NOSTR_RESOURCES_H_

// Resource IDs for bundled Nostr libraries
#define IDR_NOSTR_NDK_JS           30001
#define IDR_NOSTR_TOOLS_JS         30002
#define IDR_NOSTR_APPLESAUCE_JS    30003
#define IDR_NOSTR_NOSTRIFY_JS      30004
#define IDR_NOSTR_ALBY_SDK_JS      30005

#endif  // CHROME_GRIT_NOSTR_RESOURCES_H_